### PR TITLE
added  CODE_OF_CONDUCT

### PR DESCRIPTION
**Pull request by jivthesh**

### CODE REVIEW

**Comment by RedBrogdon** [comment]
@jivthesh, thanks for submitting a PR. Rather than adding the code of conduct to this repo, we prefer to link to the one in flutter/flutter in order to have a single source of truth.

I just checked our README.md file, though, and noticed that our link is out of date. How about removing the file you've added here, and instead, updating the link in this repo's README.d to point to the correct URL?

https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

**Comment by jivthesh** [comment]
@RedBrogdon README.md file in this repo ?so shall i update this ?

**Comment by jivthesh** [comment]
@RedBrogdon README.md in this repo should be updated to the link  https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

**Comment by RedBrogdon** [comment]
> @RedBrogdon README.md in this repo should be updated to the link https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

Exactly. The change to this PR that I would suggest is:

* Remove the new code of conduct file.
* Update README.md to use the correct link, which is the one you listed above.

**Comment by jivthesh** [comment]
@RedBrogdon Completed please check #529

**Comment by RedBrogdon** [comment]
I think we may have had a miscommunication. 😄 

Rather than adding a CODE_OF_CONDUCE file to this repo, I recommend updating the repo to point to the file at this location:

https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md

So the PR would just have a change to the README, rather than a new CODE_OF_CONDUCT file.

**Comment by RedBrogdon** [comment]
@jivthesh, it looks like you haven't had time to come back to this, so I'm going to close it for now. If you're still interested in working on the issue, though, please feel free to re-open!

**Pull request closed without merging**
