### PR TITLE
Fix sample index deployment action

### LINKED ISSUE #848: sample index deploy action is failing
Example run: https://github.com/flutter/samples/runs/3020311936

Stack trace:
```
test-cli
  /opt/hostedtoolcache/flutter/2.2.3-stable/x64/bin/cache/dart-sdk/bin/pub run test:test --reporter=expanded --platform=vm
  Failed to precompile test:test:
  /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:258:50: Error: The property 'displayString' is defined in multiple extensions for 'TargetKind' and neither is more specific.
   - 'TargetKind' is from 'package:meta/meta_meta.dart' ('/opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart').
  Try using an explicit extension application of the wanted extension or hiding unwanted extensions from scope.
          var kindNames = kinds.map((kind) => kind.displayString).toList()
                                                   ^^^^^^^^^^^^^
  /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:1950:14: Context: This is one of the extension members.
    String get displayString {
               ^^^^^^^^^^^^^
  /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/hosted/pub.dartlang.org/meta-1.7.0/lib/meta_meta.dart:91:14: Context: This is one of the extension members.
    String get displayString {
               ^^^^^^^^^^^^^
  /opt/hostedtoolcache/flutter/2.2.3-stable/x64/.pub-cache/hosted/pub.dartlang.org/analyzer-0.41.2/lib/src/error/best_practices_verifier.dart:260:36: Error: The getter 'commaSeparatedWithOr' isn't defined for the class 'List<dynamic>'.
   - 'List' is from 'dart:core'.
  Try correcting the name to the name of an existing getter, or defining a getter or field named 'commaSeparatedWithOr'.
          var validKinds = kindNames.commaSeparatedWithOr;
```

This doesn't seem like an issue with this project, though.

I created https://github.com/flutter/samples/pull/847 to fail fast if this step fails, so the deploy doesn't happen with an empty `gh-pages` branch.

### PR DESCRIPTION
**Pull request by johnpryan**
Fixes #848 

Here's a sample CI run on my fork: https://github.com/johnpryan/samples/runs/3223933935?check_suite_focus=true

### CODE REVIEW

**Comment by RedBrogdon** [comment]
You probably saw this, but I'm pinning the version of `gh-pages-action` in #861. It should be a no-op as far as this PR is concerned, since it just specifies the commit already in use, but I thought I'd make sure you were aware.

**Comment by johnpryan** [comment]
@RedBrogdon I didn't see that, I have been following https://github.com/flutter/flutter/issues/87420#issuecomment-890453040

**Comment by johnpryan** [comment]
TBR @domesticmouse

**Comment by domesticmouse** [comment]
trailing LGTM

**Pull request merged**
