### PR TITLE
[place_tracker] typo fix

### PR DESCRIPTION
**Pull request by aadarsh-patel**

### CODE REVIEW

**Comment by aadarsh-patel** [comment]
Hey @AyushBherwani1998 , Is there any way to delete my previous two PR threads?

**Comment by AyushBherwani1998** [comment]
> 
> 
> Hey @AyushBherwani1998 , Is there any way to delete my previous two PR threads?

Hey @aadarsh-patel, unfortunately there is no way to delete those PRs.

**Comment by aadarsh-patel** [comment]
I'm sad to hear that.
3 PRs just to fix a typo seems unnecessary.
I'll make sure this does not happen again.

**Comment by jddeep** [comment]
@aadarsh-patel learn how to rebase your fork and its branches to be even with upstream's master. It will help you in future in open source development and creating PRs. Thanks.

**Pull request merged**
