### PR TITLE
Update `simplistic_editor` for Flutter 3.4 beta

### PR DESCRIPTION
**Pull request by bleroux**
This PR updates `simplistic_editor` for Flutter 3.4 beta.

Fixes https://github.com/flutter/samples/issues/1443

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Please re-enable beta and master CI:

  - https://github.com/NevercodeHQ/samples/blob/Update_simplistic_editor_to_flutter_3.4/tool/flutter_ci_script_beta.sh#L42
  - https://github.com/NevercodeHQ/samples/blob/Update_simplistic_editor_to_flutter_3.4/tool/flutter_ci_script_master.sh#L44

**Review by domesticmouse — APPROVED** [review]
LGTM once CI is re-enabled

**Review by Renzo-Olivares — APPROVED** [review]
LGTM thank you!

**Comment by bleroux** [comment]
> LGTM once CI is re-enabled

@domesticmouse Thanks for the review and the tip about re-enabling CI. :+1: 
As this code fails on stable channel, can you explain me the expected process on flutter/samples for merging this PR? Do we have to wait for the next Flutter stable release before merging?

**Comment by domesticmouse** [comment]
> > LGTM once CI is re-enabled
> 
> 
> 
> @domesticmouse Thanks for the review and the tip about re-enabling CI. :+1: 
> 
> As this code fails on stable channel, can you explain me the expected process on flutter/samples for merging this PR? Do we have to wait for the next Flutter stable release before merging?

Yup, this PR will hang here until we have a new stable. I'll handle rolling this into a beta branch and then into stable.

**Comment by domesticmouse** [comment]
Can you please update this PR, or give me access to do so? It has conflicts =(

**Comment by bleroux** [comment]
> Can you please update this PR, or give me access to do so? It has conflicts =(

I have updated the PR. FYI, I disabled master channel CI because there is a new breaking change in master and this PR is targeting beta channel.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Please merge the latest from `main`. I'm preparing for a `beta` uber PR that this would be rolled into.

**Comment by domesticmouse** [comment]
Integrated into https://github.com/flutter/samples/pull/1556

**Comment by bleroux** [comment]
I have rebased this PR and updated it to comply with https://github.com/flutter/flutter/pull/76072 (add an implementation for TextInputClient.didChangeInputControl).
I have also renabled CI on master because beta and master are aligned now.

**Comment by bleroux** [comment]
@domesticmouse This PR should be ok now on beta and master.

**Comment by domesticmouse** [comment]
Thank you, re-integrated into #1556 and now everything is green on `beta` and `master`. =)

**Comment by bleroux** [comment]
> This should now be closeable. To be sure, please resolve conflicts and you should hopefully see this PR resolve to 0 files changed.

Great! Happy that those changes were useful :+1:

**Pull request closed without merging**
