### PR TITLE
Adding readme

### PR DESCRIPTION
**Pull request by RedBrogdon**
Quick poll: is it better to call this folder `experimental` or something like `master_channel`?

### CODE REVIEW

**Comment by johnpryan** [comment]
Hmm.. I like experimental better. Master channel sounds like it might mean that it only works with the flutter master channel.

**Comment by domesticmouse** [comment]
Amusingly the correlation with only working on master branch is intentional, per the content of the readme. =)

**Comment by RedBrogdon** [comment]
Right. My intent is that everything in `/experimental` run on the master channel, and everything else run on stable (and get tested against beta).

That's why `master_channel` might be a better name, but `experimental` gets the spirit of the directory across immediately.

**Comment by domesticmouse** [comment]
I'm equally happy with all the names. Actually, I'd prefer `here_be_dragons`, but I'm old school. ;-)

**Comment by RedBrogdon** [comment]
🐲

**Pull request merged**
