### PR TITLE
[linting_tool] Implement saving rules to DB

### PR DESCRIPTION
**Pull request by abd99**
Implemented saving rules to new and existing profiles.

/cc @domesticmouse

### CODE REVIEW

**Comment by domesticmouse** [comment]
Can you please update this PR so that the CI flows run?

**Review by domesticmouse — APPROVED** [review]
LGTM, I'll merge once the full CI passes.

**Comment by domesticmouse** [comment]
I'm assuming you are working on the test failures?

**Comment by abd99** [comment]
Yes, I am.

**Comment by abd99** [comment]
PTAL, @domesticmouse. I did some refactoring and set up tests with mock data, and now the tests have passed.

**Review by domesticmouse — APPROVED** [review]
LGTM

**Pull request merged**
