### PR TITLE
Updated experimental/federated_plugin/federated_plugin for upcoming release

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
fixed related issue #659  for the upcoming release.

cc: @domesticmouse,@RedBrogdon, @AyushBherwani1998

### CODE REVIEW

**Review by RedBrogdon — APPROVED** [review]
LGTM.

@AyushBherwani1998, I feel like I should let you have a look as well. It's a straightforward change, though, so if you don't have time over the next could days, I can land it regardless. 😄

**Review by AyushBherwani1998 — APPROVED** [review]
LGTM, thanks @adarsh-technocrat :)

**Comment by AyushBherwani1998** [comment]
> @AyushBherwani1998, I feel like I should let you have a look as well. It's a straightforward change, though, so if you don't have time over the next could days, I can land it regardless. 😄

Sure thing, thanks @RedBrogdon

**Comment by adarsh-technocrat** [comment]
> LGTM, thanks @adarsh-technocrat :)

Thank you @AyushBherwani1998  :)

**Comment by adarsh-technocrat** [comment]
> LGTM.
> 
> @AyushBherwani1998, I feel like I should let you have a look as well. It's a straightforward change, though, so if you don't have time over the next could days, I can land it regardless. 😄

Thank you @RedBrogdon  :)

**Review by RedBrogdon — APPROVED** [review]

**Pull request merged**
