### PR TITLE
Update samples.yaml

### PR DESCRIPTION
**Pull request by guidezpl**
Update Material related titles, descriptions.

Material 3 is a more accurate term (Material You refers to all customisation/color features on Android). Also fix a link.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
PTAL @craiglabenz

**Comment by domesticmouse** [comment]
> Do I need to do something special for links like https://flutter.github.io/samples/material_you.html to switch?

I believe @craiglabenz needs to run a manual publish step.

**Comment by guidezpl** [comment]
Okay, please let me know when you do so I can update references.

**Comment by guidezpl** [comment]
Hi @craiglabenz, PTAL

**Pull request merged**
