### PR TITLE
Added keyboard InputType in autofill form

### PR DESCRIPTION
**Pull request by Alabhya268**
Though this is sample to show autofill in forms, Its good to have keyboard type with field .

### CODE REVIEW

**Comment by Alabhya268** [comment]
@RedBrogdon ,Please have a look at this PR.

**Review by RedBrogdon — APPROVED** [review]

**Comment by RedBrogdon** [comment]
Thanks, @Alabhya268! This looks like a nice change to me. I'd like to get @johnpryan's eyes on it as well, though, since he is the original author of the app.

**Review by johnpryan — APPROVED** [review]

**Comment by Alabhya268** [comment]
Are failing tests related to this PR?

**Comment by johnpryan** [comment]
No, those are unrelated - they're only happening on the dev channel.

**Pull request merged**
