### PR TITLE
Remove uses of shrinkwrap from M3 demo

### PR DESCRIPTION
**Pull request by Piinks**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. For larger changes, raising an issue first helps
reduce redundant work.*

## Pre-launch Checklist

- [ ] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I read the [Contributors Guide].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by Piinks** [comment]
Hey @QuncCccccc I removed shrinkwrap in this commit: https://github.com/flutter/samples/pull/1534/commits/fb5084fdc8d90a2935c3f5681aa6cdbb4e040cf5

**Comment by domesticmouse** [comment]
CI is not liking this change

**Comment by Piinks** [comment]
Thank you, should be fixed now.

@QuncCccccc I did notice, on the elevation screen, where it says surface tint only, should there be shadows?

Screen Shot 2022-12-16 at 2 35 52 PM

**Comment by QuncCccccc** [comment]
> Thank you, should be fixed now.
> 
> @QuncCccccc I did notice, on the elevation screen, where it says surface tint only, should there be shadows?
> 
> Screen Shot 2022-12-16 at 2 35 52 PM

No, it should not have any shadow. Fixing!

**Review by QuncCccccc — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by Piinks** [comment]
Do you want to merge this or your PR @QuncCccccc?

**Comment by QuncCccccc** [comment]
> Do you want to merge this or your PR @QuncCccccc?

I think I still need to address some comments in my PR. I'm trying to see if I can cherry-pick these 2 commits:)

**Comment by Piinks** [comment]
Awesome! Sounds great! I think if you locally do 

```
git pull git@github.com:Piinks/samples.git testDemo
```

That might do the trick. :)

**Comment by QuncCccccc** [comment]
> Awesome! Sounds great! I think if you locally do
> 
> ```
> git pull git@github.com:Piinks/samples.git testDemo
> ```
> 
> That might do the trick. :)

Thanks! Just did it!

**Comment by QuncCccccc** [comment]
> > Thank you, should be fixed now.
> > @QuncCccccc I did notice, on the elevation screen, where it says surface tint only, should there be shadows?
> > Screen Shot 2022-12-16 at 2 35 52 PM
> 
> No, it should not have any shadow. Fixing!

Just take another look. Yes, when "Surface Tint only", the shadow is coming from the elevation level, so there should also be some shadows. It might be a little hard to see, but the "Surface Tint and Shadow" has darker shadows than "Surface Tint only" 😆. Sorry for the confusion, the headers are a little misleading. Maybe I can change it to "Surface Tint Color only", and "Shadow Color only" for the first and third headers.

**Comment by Piinks** [comment]
I am going to close this since it has been merged into the other PR. Thanks!

**Pull request closed without merging**
