### PR TITLE
game_template README.md project setup; instructing properly

### PR DESCRIPTION
**Pull request by CC-KEH**
BEFORE
image

ERROR
image

AFTER
image

image

## Pre-launch Checklist

- [✓] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [✓] I signed the [CLA].
- [✓] I read the [Contributors Guide].
- [✓] I updated/added relevant documentation (doc comments with `///`).
- [✓] All existing and new tests are passing.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Hey @filiph, should we remove the customised analysis configuration?

**Comment by CC-KEH** [comment]
Hello Sir,

I didn't change any code expect for the snippet removal in pubspec.yaml file, but the reviewer failed these checks,
Main Branch CI / Test Flutter master on ubuntu-latest (pull_request) Failing after 16m
[Details](https://github.com/flutter/samples/actions/runs/5494521895/jobs/10020543962?pr=1938)

Main Branch CI / Test Flutter master on macos-latest (pull_request) Failing after 27m
[Details](https://github.com/flutter/samples/actions/runs/5494521895/jobs/10020544015?pr=1938)

Main Branch CI / Test Flutter master on windows-latest (pull_request) Failing after 32m
[Details](https://github.com/flutter/samples/actions/runs/5494521895/jobs/10020544057?pr=1938)

I believe this error is not caused by my code changes, and request a another check, sorry for the inconvenience

**Comment by domesticmouse** [comment]
> 
> 
> Hello Sir,
> 
> 
> 
> I didn't change any code expect for the snippet removal in pubspec.yaml file, but the reviewer failed these checks,
> 
> Main Branch CI / Test Flutter master on ubuntu-latest (pull_request) Failing after 16m
> 
> [Details](https://github.com/flutter/samples/actions/runs/5494521895/jobs/10020543962?pr=1938)
> 
> 
> 
> Main Branch CI / Test Flutter master on macos-latest (pull_request) Failing after 27m
> 
> [Details](https://github.com/flutter/samples/actions/runs/5494521895/jobs/10020544015?pr=1938)
> 
> 
> 
> Main Branch CI / Test Flutter master on windows-latest (pull_request) Failing after 32m
> 
> [Details](https://github.com/flutter/samples/actions/runs/5494521895/jobs/10020544057?pr=1938)
> 
> 
> 
> I believe this error is not caused by my code changes, and request a another check, sorry for the inconvenience

I understand the problem you are pointing out, I'm just asking the author of the sample if we should approach solving the issue in another way.

Thanks again for raising this issue!

**Comment by filiph** [comment]
Sorry for the late reply. And thanks @CC-KEH for the PR!

I can't remember why the template is using `../analysis_defaults` and not a pub.dev package or the Flutter defaults here. Is that a requirement for `flutter/samples`?

We're modifying the defaults a little bit:
https://github.com/flutter/samples/blob/main/game_template/analysis_options.yaml
I remember there was some good discussion around that. 

I can't promise l'll be able to look at this anytime soon. If we remove `../analysis_defaults` and use the default lints, for example, it would be good to make sure not a) showing a lint warning with the template code, b) turning off something that's already off in the defaults.

**Comment by domesticmouse** [comment]
> I can't remember why the template is using `../analysis_defaults` and not a pub.dev package or the Flutter defaults here. Is that a requirement for `flutter/samples`?

That's a change I made, in an effort to make all of our samples comply to a common standard. I'm happy to reverse that decision if it is causing more pain than gain.

**Comment by domesticmouse** [comment]
Here y'all go: https://github.com/flutter/samples/pull/1971

**Comment by domesticmouse** [comment]
Now that `game_template` uses `flutter_lints` directly is this change still required?

**Comment by CC-KEH** [comment]
> Now that `game_template` uses `flutter_lints` directly is this change still required?

Now It wont require the change, thanks for fixing @domesticmouse!

**Pull request closed without merging**
