### PR TITLE
Update M3 app

### PR DESCRIPTION
**Pull request by guidezpl**
## Description
This PR adds all missing components and component variants as of Flutter 3.7. As all changes are available on `stable`, a subsequent PR should copy `experimental/material_3_demo` to the top-level `material_3_demo` folder.

This PR includes these changes:
- Add link to `dynamic_color` package on Color page
  Screenshot 2023-01-27 at 07 29 28
- Add TODOs with links to upstream issues for all future components / variants
- Improve usage for some components
- Add missing component variants
  - Standard bottom sheet 
    image

  - Full-screen dialog
    Screenshot 2023-01-27 at 07 29 47
    image

  
  - Navigation drawer
    Screenshot 2023-01-27 at 07 30 04
- Add missing component demos
  - Dividers
    Screenshot 2023-01-27 at 07 29 53

  - Navigation rail
    Screenshot 2023-01-27 at 07 30 09

  - Top app bar
    Kapture 2023-01-27 at 10 41 47

## Related Issues
Fixes https://github.com/flutter/samples/issues/1601

## Tests
 - Added all missing tests and made existing ones more robust

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
As this is compiling against stable channel successfully I'd suggest also updating the copy of this app in the base directory until we get to the point that master had diverged enough that stable won't compile it.

**Comment by QuncCccccc** [comment]
> As this is compiling against stable channel successfully I'd suggest also updating the copy of this app in the base directory until we get to the point that master had diverged enough that stable won't compile it.

Sounds good to me. I'm reviewing this PR and will create another PR for the stable demo. Thanks:)

**Review by QuncCccccc — APPROVED** [review]
LGTM! Glad to see more components coming. Thanks a lot:) I can do the same update to the stable demo.

**Comment by domesticmouse** [comment]
@QuncCccccc thanks!

**Comment by guidezpl** [comment]
@domesticmouse Is publishing to https://flutter-experimental-m3-demo.web.app/#/ manual?

**Comment by parlough** [comment]
@guidezpl I'm not sure who deployed that, but I don't believe it's automatic from this repository. However, the root [`material_3_demo`](https://github.com/flutter/samples/tree/main/material_3_demo) is automatically deployed to https://flutter.github.io/samples/web/material_3_demo/

**Comment by QuncCccccc** [comment]
> @domesticmouse Is publishing to https://flutter-experimental-m3-demo.web.app/#/ manual?

@guidezpl Yes, I deployed it on Firebase.

**Pull request merged**
