### PR TITLE
Update to Dart 2.12

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by mit-mit** [comment]
Thanks Brett! I won't merge this yet; we need to wait the the beta channel to be rolled.

**Comment by domesticmouse** [comment]
We are happy with experimental working on `dev` channel, so feel free to merge when ever suits. Moving it out of experimental requires it working on `stable` channel tho. =)

**Comment by mit-mit** [comment]
Got it. This is not even in dev yet, though. It should be soon, and then I'll merge it.

**Review by RedBrogdon — APPROVED** [review]
LGTM. I'll leave it to you to merge when you're ready.

**Pull request merged**
