### PR TITLE
Moved two animation vignettes into misc.

### PR DESCRIPTION
**Pull request by RedBrogdon**
Moves the vignettes featuring AnimatedPositioned and AnimatedSwitcher from `basics` to `misc`.

The basics section is designed to follow a particular progression of topics, easing the reader into more and more advanced bits of the animations API. For that reason, these two examples are better suited to the miscellaneous section.

### CODE REVIEW

**Comment by AyushBherwani1998** [comment]
@RedBrogdon we can also update the README.md and move the examples from Basics to Misc section.

**Comment by johnpryan** [comment]
That's a good point, we need to update the README too.

**Comment by jddeep** [comment]
> @RedBrogdon we can also update the README.md and move the examples from Basics to Misc section.

:+1:

**Comment by RedBrogdon** [comment]
Yep, should have updated the README. I've pushed another commit.

@johnpryan, I saw you approved, but do you mind taking another quick look? I reformatted a couple things and added a codelab link. Just want to make sure it's all good by you.

**Pull request merged**
