### PR TITLE
add thumbnails to the books example to make memory leaks easier to test

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Review by dnfield — APPROVED** [review]

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
PTAL @craiglabenz

**Comment by xster** [comment]
Sorry, I was away last week. The last error was unrelated (different package in this repo). Re-sync'ing to see if it goes away

**Comment by xster** [comment]
oh, it looks like the single PR https://github.com/flutter/flutter/pull/105291 both added a new API backgroundColor, and deprecated the previous API onPrimary, making it impossible for the same code to pass on both stable and beta

**Comment by xster** [comment]
since stable and beta conflicts for various packages in this repo, I added lint ignores for now. 

@domesticmouse let me know if there's a system in place you'd like me to follow instead? Otherwise, I'd propose running the CI every 24h even when there's no PRs, just to make sure samples code on head can build against the beta on head

**Comment by xster** [comment]
oh, I can't merge. So someone will have to do it for me

**Comment by xster** [comment]
@domesticmouse can you merge this for me?

**Comment by domesticmouse** [comment]
Nope, I'm not an authorized lander. PTAL @craiglabenz

**Comment by domesticmouse** [comment]
> @domesticmouse let me know if there's a system in place you'd like me to follow instead? Otherwise, I'd propose running the CI every 24h even when there's no PRs, just to make sure samples code on head can build against the beta on head

IIUC we are running both stable and beta CI dailiy. If not, please feel free to raise a bug and/or a PR to fix

context: https://github.com/flutter/samples/blob/main/.github/workflows/main.yml#L13

**Comment by xster** [comment]
@RedBrogdon, @craiglabenz can someone help merge?

**Comment by domesticmouse** [comment]
PTAL @craiglabenz

**Comment by xster** [comment]
does @johnpryan have merge rights? Something seems off if @domesticmouse can't merge in this repo.

**Comment by domesticmouse** [comment]
> does @johnpryan have merge rights? Something seems off if @domesticmouse can't merge in this repo. 

I can merge most PRs on this repository, I'm unsure why this one is different. 

Calling Git magicians @kevmoo and @Hixie

**Comment by dnfield** [comment]
Perhaps it wants to be against main?

**Pull request merged**
