### PR TITLE
Updated testing_app for upcoming release

### PR DESCRIPTION
**Pull request by adarsh-technocrat**
Fixed Issue #658 

cc: @domesticmouse, @RedBrogdon

### CODE REVIEW

**Review by tusharojha — CHANGES_REQUESTED** [review]
Looks like you are on the beta channel. Since the `testing_app` is based on the stable channel, so you need to checkout to stable.

**Comment by adarsh-technocrat** [comment]
> Looks like you are on the beta channel. Since the `testing_app` is based on the stable channel, so you need to checkout to stable.

Thank you @tusharojha for reviewing my PR while making changes in the repo I was in the master channel of flutter. I'm new to opensource contribution if you could provide me with some more details regarding this in steps it would helpful for me.

**Comment by tusharojha** [comment]
Hi @adarsh-technocrat!
Sorry, Actually I have just gone through the issues & PRs. So, I think @domesticmouse will give you the right steps for it as there some changes in the GitHub CI to be merged.

**Comment by adarsh-technocrat** [comment]
> Hi @adarsh-technocrat!
> Sorry, Actually I have just gone through the issues & PRs. So, I think @domesticmouse will give you the right steps for it as there some changes in the GitHub CI to be merged.

No problem @tusharojha.
Thank you!

**Comment by domesticmouse** [comment]
This is going to have to wait until after the next Flutter stable release before landing. In the mean time you'll have to keep up with master as I merge conflicting PRs like https://github.com/flutter/samples/pull/668. Sorry about that =)

**Comment by adarsh-technocrat** [comment]
> This PR is going to have to wait until after the next Flutter stable release before landing. In the mean time you'll have to keep up with master as I merge conflicting PRs like #668. Sorry about that =)

Sure @domesticmouse  just have one question is this is the right time to land this kind of PR if this is fine I may land PR for the rest of the issues which are required to update for the upcoming release.

**Comment by domesticmouse** [comment]
This is a good time to create PRs like this one, but we can't land it in master until the next Flutter stable is released.

**Comment by adarsh-technocrat** [comment]
> This is a good time to create PRs like this one, but we can't land it in master until the next Flutter stable is released.

Thanks, @domesticmouse .

**Comment by adarsh-technocrat** [comment]
Hello, @RedBrogdon  can you please review this PR as well?

**Comment by RedBrogdon** [comment]
> Hello, @RedBrogdon can you please review this PR as well?

Sure thing. The code change here is small, so it should be an easy thing to land in that sense. There's a slight trick here in that another PR for testing_app that changes the pubspec was recently landed. The best course of action would be to:

1) Rebase your PR on the current master or otherwise pull those changes into your branch, to remove the merge conflict.
2) Change the base branch for this PR to beta, since (like your other PRs) this one is working ahead of Flutter's stable branch.

It's important to do #1, since otherwise we'll have a nasty merge conflict waiting for us when the next stable release rolls out. 😄

**Review by RedBrogdon — APPROVED** [review]

**Pull request merged**
