### PR TITLE
`web/slide_puzzle` remove unmaintained sample

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @craiglabenz

**Comment by domesticmouse** [comment]
PTAL @RedBrogdon

**Review by craiglabenz — APPROVED** [review]

**Comment by craiglabenz** [comment]
Sorry this took so long - the review was rather laborious 🙃

**Comment by johnpryan** [comment]
Are we going to update the "launch app" link on the [visual sample index page](https://flutter.github.io/samples/slide_puzzle.html) or point it somewhere else?

**Comment by domesticmouse** [comment]
> Are we going to update the "launch app" link on the [visual sample index page](https://flutter.github.io/samples/slide_puzzle.html) or point it somewhere else?

We can either a) point that page at the (unmaintained) project in VGV's repo, or delete it. Preferences?

**Comment by domesticmouse** [comment]
Actually, VGV doesn't appear to host a version of the app, so we don't have anywhere to point the launch app at. Can we just remove the launch app link?

**Comment by johnpryan** [comment]
https://github.com/flutter/samples/pull/1303 LGTM

**Pull request merged**
