### PR TITLE
Cleaning up Veggie Seasons

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by sethladd** [comment]
tested locally, thank you!

Consider landing this now, I don't think we need to wait for the CI to get updated.

**Comment by ericwindmill** [comment]
> tested locally, thank you!
> 
> Consider landing this now, I don't think we need to wait for the CI to get updated.

@sethladd If you want to land now, can you remove it from CI by commenting it out in the three ci files? (e.g. tool/flutter_ci_script_beta.sh, etc)

**Review by ericwindmill — APPROVED** [review]

**Comment by ericwindmill** [comment]
I'm following up with a PR for the CI failures.

**Comment by sethladd** [comment]
thanks for the help!

**Comment by domesticmouse** [comment]
> > tested locally, thank you!
> 
> > 
> 
> > Consider landing this now, I don't think we need to wait for the CI to get updated.
> 
> 
> 
> @sethladd If you want to land now, can you remove it from CI by commenting it out in the three ci files? (e.g. tool/flutter_ci_script_beta.sh, etc)
> 
> 

Veggie Seasons should not be removed from CI.

**Pull request merged**
