### PR TITLE
adding more named and explicit imports

### PR DESCRIPTION
**Pull request by miquelbeltran**
Following the proposal in https://github.com/flutter/website/issues/7798 I have added more explicit and named imports on those places I thought it would make sense.

Let me know what you think.

## Pre-launch Checklist

- [ ] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I read the [Contributors Guide].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
I'm wondering if we should just adopt the default of `import 'dart:ui' as ui;` as opposed to having a mix of `as ui` and `show Name`

**Comment by domesticmouse** [comment]
Also, please update this PR to turn the CI green. =)

**Comment by miquelbeltran** [comment]
> I'm wondering if we should just adopt the default of `import 'dart:ui' as ui;` as opposed to having a mix of `as ui` and `show Name`

makes sense, I will do the change to see how it looks like

**Review by domesticmouse — APPROVED** [review]
Is `import 'dart:math' as math;` something we do elsewhere? It almost feels like overkill?

**Comment by miquelbeltran** [comment]
> Is `import 'dart:math' as math;` something we do elsewhere? It almost feels like overkill?

As with the other changes we have done related to https://github.com/flutter/website/issues/7798 none of them are strictly necessary.

I like the idea of having the math dependency as a named import because it allows for easier discoverability, and because the math import has a lot of top level functions and constants, so it doesn't mess with autocomplete. Although, effective Dart doesn't have a recommendation regarding this, and I don't have a strong opinion, so I'm fine to revert the change.

**Pull request merged**
