### PR TITLE
Implement case insensitive search in the samples index

### LINKED ISSUE #1517: Search queries on the Flutter Samples website are case sensitive
These two queries https://flutter.github.io/samples/#?search=game and https://flutter.github.io/samples/#?search=Game returned different results. It's probably not what we want?

### PR DESCRIPTION
**Pull request by parlough**
Closes #1517

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
@johnpryan what is required to deploy this? 

Looking at the GitHub actions log it looks like the GH Action to publish this repo is permanently broken:

```console
peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935 is not allowed to be used in flutter/samples.
```

/cc @godofredoc

**Comment by godofredoc** [comment]
> @johnpryan what is required to deploy this?
> 
> Looking at the GitHub actions log it looks like the GH Action to publish this repo is permanently broken:
> 
> ```
> peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935 is not allowed to be used in flutter/samples.
> ```
> 
> /cc @godofredoc

Can you please give it another try?

**Comment by domesticmouse** [comment]
> > @johnpryan what is required to deploy this?
> > Looking at the GitHub actions log it looks like the GH Action to publish this repo is permanently broken:
> > ```
> > peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935 is not allowed to be used in flutter/samples.
> > ```
> >   
> > /cc @godofredoc
> 
> Can you please give it another try?

@johnpryan can you please trigger a publish run? I dont appear to have permissions to re-trigger.

**Comment by johnpryan** [comment]
I'm not able to re-run workflows either, it seems.

**Pull request merged**
