### PR TITLE
bug fix in CutomTweenDemo

### PR DESCRIPTION
**Pull request by priyanshu-01**
fixes: #674

### CODE REVIEW

**Comment by priyanshu-01** [comment]
@googlebot I signed it!

**Comment by domesticmouse** [comment]
Hey @priyanshu-01 ,

Can you please add an explanation to this bug as to the issue and the proposed fix? Thanks!

brett

**Comment by priyanshu-01** [comment]
Sure @domesticmouse , I hope this explanation will help!

The bug was in samples/animations/lib/src/basics/06_custom_tween.dart

The bug was:
A RenderFlex overflowed by 8.0 pixels on the bottom.

when it happened?
The bug happened when the 'write Essay' button was clicked.

why it happened?
when the animation is completed, Whole Text with font size : 16.0 cannot be accommodated on the screen(mobile), 

How I fixed this bug?
I Wrapped the Column containing Text Widget with SingleChildScrollView so the column Size can be adjusted as per the amount of text to be accommodated.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Thank you!

**Pull request merged**
