### PR TITLE
[add-to-app/books] Added missing class declarations from the pigeon file

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes pigeon file in add-to-app/books

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
RSLGTM

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Let me know if you want me to land this PR

**Comment by gaaclarke** [comment]
> Let me know if you want me to land this PR

I'd appreciate that.  I'm not quite sure what the CI blockage is.  I was wondering if Xiao was going to clear it out with his outstanding pr.

**Comment by domesticmouse** [comment]
There are now three CI versions, one for `stable`, one for `beta`, and one for `master`. Given this sample is green on both `stable` and `beta`, I'd suggest just commenting out the `add_to_app/fullscreen/flutter_module` sample on the `Flutter CI master` [list](https://github.com/gaaclarke/samples/blob/add-to-app-missing-classes/tool/flutter_ci_script_master.sh).

From https://github.com/flutter/samples/runs/7962036109?check_suite_focus=true#step:5:262

```console
== Testing 'add_to_app/fullscreen/flutter_module' on Flutter's master channel ==
~/work/samples/samples/add_to_app/fullscreen/flutter_module ~/work/samples/samples
Running "flutter pub get" in flutter_module...                   1,852ms
Analyzing flutter_module...

   info - lib/main.dart:131:54 - 'headline5' is deprecated and shouldn't be used. Use headlineSmall instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
   info - lib/main.dart:138:58 - 'headline5' is deprecated and shouldn't be used. Use headlineSmall instead. This feature was deprecated after v3.1.0-0.0.pre.. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

**Pull request merged**
