### PR TITLE
Publish `web_embedding`

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

Co-authored-by: Mark Thompson <2554588+MarkTechson@users.noreply.github.com>
Co-authored-by: David Iglesias <ditman@gmail.com>

### CODE REVIEW

**Comment by ditman** [comment]
Can you please amend the commit and add the following at the end:

```


Co-authored-by: Mark Thompson <2554588+MarkTechson@users.noreply.github.com>
Co-authored-by: David Iglesias <ditman@gmail.com>
```

At the end of the commit message, to preserve authorship? I don't care about mine too much, but at least add Mark's at the end of the commit message, so his mugshot shows in the repo history of this commit!

**Review by ditman — APPROVED** [review]
LGTM! Let's go!

**Comment by domesticmouse** [comment]
I'll land once CI turns (mostly) green. =)

**Comment by ditman** [comment]
Thanks Brett!

**Pull request merged**
