### PR TITLE
Add windows support to desktop photo search.

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
@stuartmorgan I'm holding this in draft until you are ready for me to land this.

**Comment by domesticmouse** [comment]
Fixes: https://github.com/flutter/flutter/issues/65863

**Comment by stuartmorgan** [comment]
You can regenerate the `windows` folder now with the latest master of Flutter, then it will be good to land.

**Comment by domesticmouse** [comment]
@stuartmorgan Windows directory re-generated. PTAL

**Review by stuartmorgan — APPROVED** [review]
LGTM. I assume all contents of `windows/` was stock template, so didn't review it closely.

**Pull request merged**
