### PR TITLE
Initial date planner app

### PR DESCRIPTION
**Pull request by mit-mit**
Initial **experimental** date planner iOS sample.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by mit-mit** [comment]
CI failures are unrelated to this PR:
```
== Testing 'add_to_app/fullscreen/android_fullscreen' on Flutter's stable channel ==
...
FAILURE: Build failed with an exception.
...
```

**Comment by domesticmouse** [comment]
@ericwindmill to confirm maintenance capacity

**Comment by ericwindmill** [comment]
> @ericwindmill to confirm maintenance capacity

I expected this PR and confirm that we have a maintenance plan. I talked to Kate about adding a couple iOS samples the other day. 

But thanks for looking out, truly.

**Review by domesticmouse — APPROVED** [review]

**Comment by Piinks** [comment]
> we have a maintenance plan.

Thank you, yes! Can confirm. 🙂

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Pull request merged**
