### PR TITLE
[infinite_list] Web folder added in infinite_list

### PR DESCRIPTION
**Pull request by yash1200**
In this PR, I have added the web folder in infinite_list.

### CODE REVIEW

**Comment by domesticmouse** [comment]
@RedBrogdon do we have a position on adding web directory to stable samples? Looking at this PR, I see we are winding up with `pubspec.lock` with Dart 2.10 level deps. I'm also concerned that some of the travis tests are failing due to Android licenses not being accepted?

**Comment by RedBrogdon** [comment]
Several of our existing stable samples have web (and desktop) folders. It looks like you were involved in creating them. 😄 

https://github.com/flutter/samples/pull/223/files

I don't think it's a problem (nor is the failed test, which seems to be corrected), but we *do* need to keep the pubspec locked to the stable version. @yash1200, can you run `flutter channel stable`, then `flutter pub get` and update your pull request?

**Comment by yash1200** [comment]
It's done @RedBrogdon .

**Review by RedBrogdon — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
