### PR TITLE
Upgrade `android_fullscreen` to AGP 8.1.4

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
I'm out of my depth on how to fix up this code. 

@RedBrogdon any ideas who we should hassle about upgrading this Android code?

**Comment by RedBrogdon** [comment]
> @RedBrogdon any ideas who we should hassle about upgrading this Android code?

@reidbaker, do you (or your team) have any recommendations? This is the oldest add-to-app sample for Android.

**Comment by reidbaker** [comment]
I believe you need pull request #flutter/flutter/pull/137370 which might not be in 3.16. In the meantime you can try to update to AGP 7.6.*.

**Comment by domesticmouse** [comment]
Closing out for now

**Pull request closed without merging**
