### PR TITLE
Add `flutter_lints` to `experimental/federated_plugin/federated_plugin_macos`

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by AyushBherwani1998** [comment]
Just a question, we didn't add `analysis_options.yaml` because it didn't have any Dart code.

**Comment by domesticmouse** [comment]
Adding @RedBrogdon for his thoughts. I'd lean towards adding it everywhere for ease of compliance checking, but it's not something I'm attached to.

**Comment by RedBrogdon** [comment]
For consistency's sake, I'd support adding it as well.

**Comment by AyushBherwani1998** [comment]
Thanks for clarification :)

**Review by AyushBherwani1998 — APPROVED** [review]
LGTM

**Pull request merged**
