### PR TITLE
`simplistic_calculator`: Breaking apart into a bunch of steps

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @sfshaza2 =)

**Review by sfshaza2 — APPROVED** [review]
What a massive effort! But yean, it lgtm.

**Comment by domesticmouse** [comment]
Thanks @sfshaza2!

**Comment by abd99** [comment]
This looks nice. Is this going to be used in a talk? I can see your VSCode typer files.

**Comment by domesticmouse** [comment]
> This looks nice. Is this going to be used in a talk? I can see your VSCode typer files.

Yup, I'm using it for a couple of Flutter Festival talks here in Australia. Feel free to adopt and adapt 😎

**Pull request merged**
