### PR TITLE
[add-to-app] Fixed typo in README.md

### PR DESCRIPTION
**Pull request by Swayam221**
Fixed a typo in add-to-app/README.md. Changed 'Fluter' to 'Flutter'.

### CODE REVIEW

**Review by arteevraina — APPROVED** [review]

**Comment by arteevraina** [comment]
@Swayam221 Thanks for the PR :confetti_ball:  ! The changes look perfect now. Though, the title of PR is self-explanatory but it's a good practice to add a bit of description for the PR even if it is a small one :)

**Comment by Swayam221** [comment]
> @Swayam221 Thanks for the PR 🎊 ! The changes look perfect now. Though, the title of PR is self-explanatory but it's a good practice to add a bit of description for the PR even if it is a small one :)
I guess a description can still be added right?

**Comment by arteevraina** [comment]
image
Yes, click on this button and edit it.

**Comment by Swayam221** [comment]
> image
> Yes, click on this button and edit it.

@arteevraina Thankyou! will keep in mind to provide a description always from now on. I have updated the description.😃

**Comment by Alabhya268** [comment]
@Swayam221 ,I noticed that you have open issue for this PR, Next time please also mention the issue related to the PR.  : )

**Comment by Swayam221** [comment]
> @Swayam221 ,I noticed that you have open issue for this PR, Next time please also mention the issue related to the PR. : )
@Alabhya268 Sorry!😅 I am relatively new to open source. Thanks for the advice. Should I mention it in the description?😅

**Review by RedBrogdon — APPROVED** [review]

**Comment by RedBrogdon** [comment]
Fixes #705.

**Pull request merged**
