### PR TITLE
[ci] Reduce npm update noise.

### PR DESCRIPTION
**Pull request by ditman**
Take only security and major version updates for the `ng-flutter` sample.

(Similar to what's done [here](https://github.com/flutter/packages/blob/main/.github/dependabot.yml#L33-L35))

## Issues

* Fixes https://github.com/flutter/samples/issues/1809

_See [docs about the `update-types` dependabot setting](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore)._

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by ditman** [comment]
I hope this drastically reduces the amount of dependabot updates for the npm bits of the `ng-flutter` sample!

**Comment by parlough** [comment]
This is a good idea, thanks! I'll leave the choice up to @johnpryan though :)

**Comment by ditman** [comment]
SGTM! He proposed maybe doing this in the closed issue, I'm just reproducing what we already do in flutter/packages (for Gradle deps), but feel free to discard this!

**Review by domesticmouse — APPROVED** [review]

**Comment by johnpryan** [comment]
LGTM

**Pull request merged**
