### PR TITLE
[web] Publish ng-flutter example.

### PR DESCRIPTION
**Pull request by ditman**
This PR publishes a possible Angular - Flutter Web integration app.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

Co-authored-by: Mark Thompson <2554588+MarkTechson@users.noreply.github.com>

### CODE REVIEW

**Comment by ditman** [comment]
Since this is an angular app, I'm not sure if we even want to connect it to the CI tooling :S

**Comment by domesticmouse** [comment]
> Since this is an angular app, I'm not sure if we even want to connect it to the CI tooling :S

Is there a dependabot config we should add to keep the sample up to date?

**Review by domesticmouse — APPROVED** [review]

**Comment by ditman** [comment]
> Is there a dependabot config we should add to keep the sample up to date?

Never setup dependabot myself, so: unsure.

However, there's two places where updates should happen:

* https://github.com/flutter/samples/blob/beta/web_embedding/ng-flutter/package.json -> `npm` updates (angular)
* https://github.com/flutter/samples/blob/beta/web_embedding/ng-flutter/flutter/pubspec.yaml -> `pub` updates (flutter)

**Comment by johnpryan** [comment]
I think this is the only change needed for dependabot: https://github.com/flutter/samples/pull/1774

**Pull request merged**
