### PR TITLE
added firebase links

### PR DESCRIPTION
**Pull request by Nandak99**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. For larger changes, raising an issue first helps
reduce redundant work.*

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
Can you please expand on the problem this PR is fixing? It'd probably help to have an Issue raised at https://github.com/flutter/samples/issues that explains the underlying issue, with a reproduction case.

**Comment by domesticmouse** [comment]
Also, signing the CLA is required.

**Comment by craiglabenz** [comment]
LGTM an associated issue explaining the situation and, of course, a CLA signature.

**Comment by domesticmouse** [comment]
Hey @Nandak99, it's been almost a month since we asked you to sign the CLA. Is this something you are working on, or should we close out this PR?

**Comment by domesticmouse** [comment]
Closing out due to inactivity

**Pull request closed without merging**
