### PR TITLE
[Animation] Added title to Animation Demos

### PR DESCRIPTION
**Pull request by Alabhya268**
Issue- #564 

Is it good or anything needs to be changed?

### CODE REVIEW

**Comment by Alabhya268** [comment]
@RedBrogdon Please review this PR.

**Comment by Alabhya268** [comment]
@RedBrogdon Please review this PR.

**Comment by Alabhya268** [comment]
@RedBrogdon Please review this PR.

**Comment by tusharojha** [comment]
Hi @Alabhya268, usually maintainers review pr on the weekdays. So, you can expect it to be reviewed by Monday.

**Comment by Alabhya268** [comment]
> 
> 
> Hi @Alabhya268, usually maintainers review pr on the weekdays. So, you can expect it to be reviewed by Monday.

@tusharojha, Thanks for letting me know.

**Review by RedBrogdon — APPROVED** [review]

**Comment by RedBrogdon** [comment]
LGTM. Thanks for the PR!

**Pull request merged**
