### PR TITLE
[place_tracker] fixed a typo

### PR DESCRIPTION
**Pull request by aadarsh-patel**
CC @jddeep

### CODE REVIEW

**Comment by AyushBherwani1998** [comment]
Hey @aadarsh-patel, checkout the master branch. Pull the changes from the samples repo. Checkout a new branch and do the changes.

**Comment by aadarsh-patel** [comment]
Hey @AyushBherwani1998 ,
Thanks for helping me out.
But I did the same thing and it didn't worked.
1. `git checkout master`
2. `git pull upstream master`
3. `git checkout -b typobranch`
4. *doing changes
5. Commit
6 Pull
7. Pull request

**Comment by AyushBherwani1998** [comment]
I did check out your master branch. You master branch is already five commits ahead. You have some commits which are not merged with this repo.

**Comment by aadarsh-patel** [comment]
Thank you so much for your time to helping me out. I just created a new fork.

**Pull request closed without merging**
