### PR TITLE
Navigation Rail

### PR DESCRIPTION
**Pull request by mohak852**
Added Navigation Rail in the flutter sample.
#477

### CODE REVIEW

**Comment by domesticmouse** [comment]
It'd be helpful to have a sketch of a design to cover what this sample is doing, and a screenshot. 

I suspect it should go into experimental, because desktop isn't supported on `stable` or `beta`.

**Comment by mohak852** [comment]
> It'd be helpful to have a sketch of a design to cover what this sample is doing, and a screenshot.
> 
> I suspect it should go into experimental, because desktop isn't supported on `stable` or `beta`.

Added The screenshots and a brief introduction about the repo.
@domesticmouse  Please check and tell me for any other suggestions

**Comment by rubensdemelo** [comment]
NavigationRail doc api already have an example https://api.flutter.dev/flutter/material/NavigationRail-class.html

**Comment by mohak852** [comment]
This is the repo of flutter samples @rubensdemelo

**Comment by rubensdemelo** [comment]
> This is the repo of flutter samples @rubensdemelo

@mohak852 I know that. My point is that your app is exaclty the same on NavigationRail doc.

**Comment by domesticmouse** [comment]
Hi @mohak852,

Further to @rubensdemelo's point, a sample has to be more than the demonstration code in the API documentation. It needs to pull together more of a story, showing how multiple moving pieces work together.

The reason for this higher bar is that samples in this repository represent a maintenance burden that need to be reviewed and updated with every new release of Dart and Flutter.

**Comment by mohak852** [comment]
Ok, I will design more pages and then add to it.That will be ok @domesticmouse

**Comment by RedBrogdon** [comment]
@mohak852, while I appreciate that you're interested in creating a new sample for the Flutter community, I need to ask you to maintain it in a different repo. This repository is not meant to be the one and only place for people to come to get good Flutter sample code. It's mostly meant to be a repository for the samples that happen to be created by folks on the Flutter team at Google. Please see our contributor's guide for more details:

https://github.com/flutter/samples/blob/master/CONTRIBUTING.md

Please don't let this dissuade you from building a sample app, though! There are many great devs building samples in their own accounts that are just as useful and just as appreciated as those you find here. There are also many ways to publicize your work once it's finished, which is something you can also learn about in our contributor's guide.

**Pull request closed without merging**
