### PR TITLE
Adds season display to details screen.

### PR DESCRIPTION
**Pull request by RedBrogdon**
Adds a text description of a veggie's harvest seasons to the details screen.

### CODE REVIEW

**Comment by RedBrogdon** [comment]
UI preview:

image

**Comment by xster** [comment]
Just a random thought / I have no design taste: can we turn them into like autumn leaf / snow flake icons instead of spelling them full out?

**Comment by RedBrogdon** [comment]
We can, but it'd be a question of where to get the icons from. That's how we ended up with the weird "season circles" that were in the previous version and drew criticism from reviewers. 

CupertinoIcons has a snowflake that could be used for winter and a sun icon that could stand in for summer, but I don't know what we'd do for spring and fall.

**Comment by RedBrogdon** [comment]
Looks like I can pull in some useful icons using @brianegan's FontAwesome package, so I've done that. Removed the text description of seasons and placed the icons up near the top of the details hierarchy.

**Pull request merged**
