### PR TITLE
[provider shopper] Upgrade project

### PR DESCRIPTION
**Pull request by ttakehiro**
upgrade provider shopper

- Unified style
- Change deprecation to recommendation
- upgrade package

### CODE REVIEW

**Comment by jddeep** [comment]
@ttakehiro Also please make sure you sign the CLA for your further PRs. And you can close this for the travis builds with respect to the `stable` version of flutter here. Thanks.

**Comment by ttakehiro** [comment]
Sorry, I didn't read  [this](https://github.com/flutter/samples/blob/master/CONTRIBUTING.md#a-few-ground-rules) readme.
I'll be careful in the future.

What to do next?
Should I close this repository?

Finally, sorry.
I don't understand polite English, so I'm translating everything with google transform.

**Comment by jddeep** [comment]
It's completely okay 😊 @ttakehiro. We are aways open to contributions in this community.
About this Pull Request, yes you can close it for now.
Thanks :)

**Comment by GOVINDDIXIT** [comment]
@ttakehiro You can close this PR and can look on existing issues or create new issues to solve if you want. 😃

**Comment by ttakehiro** [comment]
@GOVINDDIXIT 
Thankyou very match.


This PR's Flutter master version, but this project is Flutter stable version.
So, close this PR.

**Comment by RedBrogdon** [comment]
@super-tkg, プルリクエストをありがとうございました!

As others have pointed out, the examples in this repo use the stable channel. If you see any bugs, though, don't be shy about telling us. 😄

**Pull request closed without merging**
