### PR TITLE
[beta updates] fullscreen

### PR DESCRIPTION
**Pull request by craiglabenz**
Updates `fullscreen` app for Dart 2.17

### CODE REVIEW

**Comment by domesticmouse** [comment]
I'm curious why this is passing on stable. Did you bump the min dart version to 2.17.0-0?

**Review by domesticmouse — APPROVED** [review]
Set the min Dart version to 2.17.0-0

**Comment by craiglabenz** [comment]
Yep, I did update that in this PR. It's way more difficult to tell than would be ideal, though, because I somehow seem to have a few straggler commits from Andrew in all of my beta PRs. Let's get that ironed out soon so these are a lot less noisy, @domesticmouse.

**Comment by domesticmouse** [comment]
That looks waaay betterer

**Pull request merged**
