### PR TITLE
Update filled button and filled tonal button

### PR DESCRIPTION
**Pull request by QuncCccccc**
Instead of using ElevatedButton with filled, filled tonal style, this pr shows FilledButton and FilledButton.tonal without extra style configuration.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by darrenaustin — APPROVED** [review]
LGTM.

There are some check failures below. Are those because they are not using the master branch?

**Comment by QuncCccccc** [comment]
> LGTM.
> 
> There are some check failures below. Are those because they are not using the master branch?

I think so. Need to double check with @domesticmouse . Looks like these tests are not related to the M3 app.

**Comment by domesticmouse** [comment]
@QuncCccccc please LGTM https://github.com/flutter/samples/pull/1395 and https://github.com/flutter/samples/pull/1396 which should hopefully turn this PR green

**Review by domesticmouse — APPROVED** [review]

**Comment by QuncCccccc** [comment]
> @QuncCccccc please LGTM #1395 and #1396 which should hopefully turn this PR green

LGTMed both PRs:)

**Comment by domesticmouse** [comment]
Please bring this PR up to date with `main`. That should be enough to turn the CI pipelines green

**Pull request merged**
