### PR TITLE
Drop `platform_channels`

### PR DESCRIPTION
**Pull request by domesticmouse**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by Gustl22** [comment]
Is there an alternative sample? Or is there a reason to have it dropped 😅

**Comment by domesticmouse** [comment]
This sample is currently broken. A better place to investigate platform channels is https://docs.flutter.dev/platform-integration/platform-channels

**Comment by AyushBherwani1998** [comment]
Hey @domesticmouse @RedBrogdon, I hope you are doing good. just saw this, anyway I can help to fix the samples?

**Comment by Gustl22** [comment]
> This sample is currently broken.

Thanks for the answer. Personally I prefer to have a working example, where issues can be easily tested against and reference the sample code also in the issue tracker (as minimal reproduction sample), without the need to go through foreign code. This also reduces the risk of having a broken `platform_channel` library. Recently I had an [issue](https://github.com/flutter/flutter/issues/126209) with Linux, which could have been avoided, I guess, if this was implemented once in a sample library. If the sample code is broken, it's likely that all other users have this issue, too.

It's not always obvious how to solve certain problems without having a complete working code, as some details are not revealed in the docs.

But I understand, if this may is not worth the effort and you may have good reasons to drop the sample, but I don't really see them :)

**Comment by domesticmouse** [comment]
> Hey @domesticmouse @RedBrogdon, I hope you are doing good. just saw this, anyway I can help to fix the samples?

I tried running this sample up on iOS, and it spat the dummy:

```console
flutter run -d iphone
Launching lib/main.dart on iPhone 14 in debug mode...
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Running Xcode build...                                                  
 └─Compiling, linking and signing...                      2,501ms
Xcode build done.                                           12.1s
Failed to build iOS app
Swift Compiler Error (Xcode): Cannot find 'AccelerometerStreamHandler' in scope
/Users/brettmorgan/Documents/GitHub/samples/platform_channels/ios/Runner/AppDelegate.swift:45:127


Could not build the application for the simulator.
Error launching application on iPhone 14.
```

Any ideas on how to fix?

**Pull request closed without merging**
