### PR TITLE
Update M3 Demo in the Base Directory

### PR DESCRIPTION
**Pull request by QuncCccccc**
This PR is to copy the changes in the experimental Material3 demo app and update the stable M3 demo.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
Please wait until https://github.com/flutter/samples/pull/1617 is landed and integrated. That PR should fix the red CI on this PR.

**Comment by domesticmouse** [comment]
This PR is also blocked on https://github.com/flutter/samples/pull/1617 landing and integrating

**Comment by QuncCccccc** [comment]
> Please wait until #1617 is landed and integrated. That PR should fix the red CI on this PR.

I see. Thanks a lot!

**Comment by domesticmouse** [comment]
> > Please wait until #1617 is landed and integrated. That PR should fix the red CI on this PR.
> 
> I see. Thanks a lot!

It's landed. Please bring this PR up to date with master.

**Review by domesticmouse — APPROVED** [review]
LGTM once CI turns green

**Comment by QuncCccccc** [comment]
> > > Please wait until #1617 is landed and integrated. That PR should fix the red CI on this PR.
> > 
> > 
> > I see. Thanks a lot!
> 
> It's landed. Please bring this PR up to date with master.

Just rebased master. Thanks:)!

**Pull request merged**
