### PR TITLE
Recreate Renzo-Olivares's `simplistic_editor` fix

### PR DESCRIPTION
**Pull request by domesticmouse**
Replaces https://github.com/flutter/samples/pull/1979

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
@Renzo-Olivares please check that I have recreated https://github.com/flutter/samples/pull/1979 faithfully. Thanks!

**Review by Renzo-Olivares — APPROVED** [review]
LGTM thanks for taking care of this!

**Comment by domesticmouse** [comment]
@Renzo-Olivares Can the `onShare` and `onSearchWeb` be null handlers? Or do we need something more complete?

**Comment by Renzo-Olivares** [comment]
From my knowledge `onShare` and `onSearchWeb` aren't available in `stable` yet. Should we still add them here?

**Comment by domesticmouse** [comment]
> From my knowledge `onShare` and `onSearchWeb` aren't available in `stable` yet. Should we still add them here?

I'm setting this PR up as a patch to land when the Q4 stable release happens. 

Assuming `onShare` and `onSearchWeb` are slated to release in the Q4 stable then yup, we should add them to this PR.

**Comment by Renzo-Olivares** [comment]
In that case then `onShare` and `onSearchWeb` should have more complete implementations. Something along these lines. This is taken straight from `editable_text.dart` in the framework.

```dart
  /// Launch a web search on the current selection,
  /// as in the "Search Web" edit menu button on iOS.
  ///
  /// Currently this is only implemented for iOS.
  Future<void> _searchWebForSelection(SelectionChangedCause cause) async {
    final String text = textEditingValue.selection.textInside(textEditingValue.text);
    if (text.isNotEmpty) {
      await SystemChannels.platform.invokeMethod(
        'SearchWeb.invoke',
        text,
      );
    }
  }

  /// Launch the share interface for the current selection,
  /// as in the "Share" edit menu button on iOS.
  ///
  /// Currently this is only implemented for iOS.
  Future<void> _shareSelection(SelectionChangedCause cause) async {
    final String text = textEditingValue.selection.textInside(textEditingValue.text);
    if (text.isNotEmpty) {
      await SystemChannels.platform.invokeMethod(
        'Share.invoke',
        text,
      );
    }
  }
```

**Pull request merged**
