### PR TITLE
Remove bitcode=NO from add-to-app flows

### PR DESCRIPTION
**Pull request by jmagman**
See https://github.com/flutter/flutter/issues/39359.

### CODE REVIEW

**Comment by RedBrogdon** [comment]
LGTM. You still need me to TestFlight a new version of the iOS sample app with bitcode enabled, right?

**Comment by jmagman** [comment]
> LGTM. You still need me to TestFlight a new version of the iOS sample app with bitcode enabled, right?

Probably a good thing to test out, but I'm not familiar with how/when sample apps are deployed.  @dnfield do you see a problem with this?

**Comment by RedBrogdon** [comment]
The iOS sample, Veggie Seasons, is the only one that gets published, and it's done on an ad hoc basis -- whenever we make an improvement or there's something new in the SDK to check out, for the most part.

**Comment by jmagman** [comment]
> The iOS sample, Veggie Seasons, is the only one that gets published, and it's done on an ad hoc basis -- whenever we make an improvement or there's something new in the SDK to check out, for the most part.

Ah, I now see https://github.com/flutter/flutter/issues/39575, so it sounds like it's still needed, though this change is only part of my effort to scrub the add-to-app flows.  Looks like there's issues with devicelab not having a new enough version of Xcode, so the other examples haven't been updated. https://github.com/flutter/flutter/pull/39912

**Comment by jmagman** [comment]
> Looks like there's issues with devicelab not having a new enough version of Xcode, so the other examples haven't been updated. [flutter/flutter#39912](https://github.com/flutter/flutter/pull/39912)

This means when bitcode is turned off everywhere, if Travis does any iOS sample builds, it will need to be running the same version of Xcode used to build the engine.

**Comment by dnfield** [comment]
The same or newer :)  But I'm not seeing any jobs to build the iOS binaries on Travis...

**Pull request merged**
