### PR TITLE
Add surfaceTint, outlineVariant, scrim and re-arrange

### PR DESCRIPTION
**Pull request by hrishikesh-kadam**
Re-arrange colors according to [Baseline color scheme tokens]

[Baseline color scheme tokens]: https://m3.material.io/styles/color/the-color-system/tokens#e26e130c-fa67-48e1-81ca-d28f6e4ed398

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @QuncCccccc

**Comment by domesticmouse** [comment]
Please pull from `main` to fix master CI failures

**Comment by hrishikesh-kadam** [comment]
@domesticmouse Rebased on main

**Review by QuncCccccc — COMMENTED** [review]
Thanks for the contribution! This looks good to me. Could you do the same change for `experimental/material_3_demo/lib/color_palettes_screen.dart`?

**Comment by domesticmouse** [comment]
PTAL @QuncCccccc

**Review by QuncCccccc — APPROVED** [review]
LGTM:) Thanks for the contribution!

**Comment by domesticmouse** [comment]
Thanks for the review @QuncCccccc!

**Pull request merged**
