### PR TITLE
Add Testing sample

### PR DESCRIPTION
**Pull request by abd99**
This PR lands testing sample in master.

/cc @domesticmouse

### CODE REVIEW

**Comment by domesticmouse** [comment]
Nope, we will land it in `flutter:master` from `flutter:testing_sample`. See https://github.com/flutter/samples/pull/500

**Comment by abd99** [comment]
So, should I create the same PR into `flutter:testing_sample`?

**Comment by domesticmouse** [comment]
Yup, updating `flutter:testing_sample` will update #500. I hope. =)

**Comment by domesticmouse** [comment]
Re-opening this PR as it may be a better PR than #500.

**Comment by abd99** [comment]
Yes, it'll be a lot easier to review and won't even mess things up in `add_to_app`

**Comment by abd99** [comment]
But I had deleted the branch yesterday, can we still re-open it?

**Comment by domesticmouse** [comment]
You might need to create a new branch, pull from `flutter:testing_sample` and rebase. @RedBrogdon if you have a better suggestion, please chime in...

**Pull request closed without merging**
