### PR TITLE
Another context menus example: custom menu

### PR DESCRIPTION
**Pull request by justinmc**
I was finding this example useful myself, so I thought I would add it here.  It shows how to make the menu framing and positioning out of custom widgets while keeping the default buttons.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Any ideas on why the tests are failing on master? If the code can't be made to pass on `master` and `beta` it's probably worth commenting out the entry in the `master` CI with a TODO that gives guidance on what will need to be done to rectify the situation.

**Review by domesticmouse — APPROVED** [review]
LGTM once all the CIs are green

**Comment by domesticmouse** [comment]
> Ah it's just my navigation to the example. I'm using `dragUntilVisible` to scroll the list item into view, but it strangely fails with certain scroll amounts. There's probably a better way to do it, but I'll try another value that works locally.

The CI still isn't happy. I'd go with commenting it out of the `master` CI train. The `master` CI is there mainly for experimental Material 3 samples which weren't compatible with `beta` during initial development.

**Comment by justinmc** [comment]
@domesticmouse CI is green.  Was that due to your PR (https://github.com/flutter/samples/pull/1579) and my merge, or is there a worry that this is flaky?

**Comment by domesticmouse** [comment]
> @domesticmouse CI is green.  Was that due to your PR (https://github.com/flutter/samples/pull/1579) and my merge, or is there a worry that this is flaky?

I commented this project out of master CI. It now requires a `code format` change on master.

**Comment by justinmc** [comment]
Got it, thanks!

**Pull request merged**
