### PR TITLE
Restores `add_to_app/multiple_flutters/multiple_flutters_ios` to the iOS CI list

### PR DESCRIPTION
**Pull request by RedBrogdon**
This should not be merged until the next stable release.

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]
LGTM, land after FlutterEngineGroup hits stable.

**Comment by gaaclarke** [comment]
I rebased this for you to kickoff CI now that 2.0 is on stable.

**Comment by RedBrogdon** [comment]
I'm not sure why these tests aren't passing. It looks like the GHA bots are pulling in an old version of the master branch code.

If the iOS CI script works, I'm inclined to call it a flake and land anyway. Thoughts?

**Comment by gaaclarke** [comment]
@RedBrogdon It looks like there are new deprecations in 2.0 that are causing problems with some of the tests, unrelated to this change.  I can look into addressing them.  I'll land this in the meantime to make things easier.

**Comment by gaaclarke** [comment]
Oh, looks like you already addressed the issues this CI was choking on, weird, OK.

**Pull request merged**
