### PR TITLE
Simplify experimental pedometer example

### PR DESCRIPTION
**Pull request by liamappelbe**
Since ffigen added support for [`NativeCallable.listener`](https://api.flutter.dev/flutter/dart-ffi/NativeCallable/NativeCallable.listener.html) to its ObjC bindings, this example can be simplified. We can replace the `Dart_Port` logic with `ObjCBlock.listener`, which lets us get rid of most of the native code.

We still need a small bit of native code to `retain` a reference to the callback's arguments before invoking the listener, otherwise the arguments may be ref counted and deleted before the Dart side of the callback is invoked. See https://github.com/dart-lang/native/issues/835

### CODE REVIEW

**Comment by liamappelbe** [comment]
Nevermind, I think this is blocked on another small tweak to the ObjC bindings.

**Comment by liamappelbe** [comment]
Actually I managed to fix the bug without ffigen changes. Ready for review.

**Comment by domesticmouse** [comment]
Looks like there are CI issues:

```console
warning - example/lib/steps_repo.dart:5:8 - Unused import: 'dart:isolate'. Try removing the import directive. - unused_import
warning - example/lib/steps_repo.dart:102:49 - The receiver can't be null, so the null-aware operator '?.' is unnecessary. Try replacing the operator '?.' with '.'. - invalid_null_aware_operator
warning - example/lib/steps_repo.dart:104:61 - The '!' will have no effect because the receiver can't be null. Try removing the '!' operator. - unnecessary_non_null_assertion
```

**Comment by liamappelbe** [comment]
> Looks like there are CI issues:

Fixed

**Comment by domesticmouse** [comment]
PTAL @leighajarett

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
