### PR TITLE
Update VeggieSeasons Settings screen to use CupertinoList

### PR DESCRIPTION
**Pull request by mit-mit**
## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I read the [Contributors Guide].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md
[Contributors Guide]: https://github.com/flutter/samples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by mit-mit** [comment]
cc @sethladd

**Review by domesticmouse — APPROVED** [review]

**Comment by mit-mit** [comment]
That was fast, thanks @domesticmouse !

**Comment by domesticmouse** [comment]
> That was fast, thanks @domesticmouse !

Do you want me to land this, or wait for @sethladd to review?

**Comment by mit-mit** [comment]
Let's go ahead and land on green CI, please!

**Pull request merged**
